version: '3.9'

services:
  nameservice:
    build: ./nameservice
    ports:
      - "5000:5000"

  dispatcher:
    build: ./dispatcher
    ports:
      - "4000:4000"
    depends_on:
      - nameservice

  worker-reverse:
    build: ./worker
    command: ["python", "worker.py", "reverse"]
    ports:
      - "6001:6000"
    depends_on:
      - dispatcher
      - nameservice

  client:
    build: ./client
    stdin_open: true
    tty: true
    depends_on:
      - dispatcher

  monitoring:
    build: ./monitoring
    ports:
      - "7000:7000"
    depends_on:
      - dispatcher