version: '3.9'

services:
  nameservice:
    build: 
      context: .
      dockerfile: nameservice/Dockerfile
    volumes:
      - logs:/logs
    environment:
      - LOG_DIR=/logs
    ports:
      - "5001:5001"
    networks:
      - tasknet

  dispatcher:
    build: 
      context: .
      dockerfile: dispatcher/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - nameservice
    volumes:
      - logs:/logs
    environment:
      - LOG_DIR=/logs
    networks:
      - tasknet

  monitoring:
    build:
      context: .
      dockerfile: monitoring/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - dispatcher
      - nameservice
    volumes:
      - logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_DIR=/logs
    networks:
      - tasknet


  worker-reverse:
    build:
      context: .
      dockerfile: worker/Dockerfile
    entrypoint: ["python", "worker.py", "reverse"]
    ports:
      - "6001:6000"
    depends_on:
      - dispatcher
      - nameservice
    volumes:
      - logs:/logs
    environment:
      - LOG_DIR=/logs
    networks:
      - tasknet

  worker-hash:
    build:
      context: .
      dockerfile: worker/Dockerfile
    entrypoint: ["python", "worker.py", "hash"]
    ports:
      - "6002:6000"
    depends_on:
      - dispatcher
      - nameservice
    volumes:
      - logs:/logs
    environment:
      - LOG_DIR=/logs
    networks:
      - tasknet

  worker-sum:
    build:
      context: .
      dockerfile: worker/Dockerfile
    entrypoint: ["python", "worker.py", "sum"]
    ports:
      - "6003:6000"
    depends_on:
      - dispatcher
      - nameservice
    volumes:
      - logs:/logs
    environment:
      - LOG_DIR=/logs
    networks:
      - tasknet

  worker-upper:
    build:
      context: .
      dockerfile: worker/Dockerfile
    entrypoint: ["python", "worker.py", "upper"]
    ports:
      - "6004:6000"
    depends_on:
      - dispatcher
      - nameservice
    volumes:
      - logs:/logs
    environment:
      - LOG_DIR=/logs
    networks:
      - tasknet

  worker-wait:
    build:
      context: .
      dockerfile: worker/Dockerfile
    entrypoint: ["python", "worker.py", "wait"]
    ports:
      - "6005:6000"
    depends_on:
      - dispatcher
      - nameservice
    volumes:
      - logs:/logs
    environment:
      - LOG_DIR=/logs
    networks:
      - tasknet

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - dispatcher
      - nameservice
    volumes:
      - logs:/logs
    environment:
      - LOG_DIR=/logs
    networks:
      - tasknet


volumes:
  logs: {}
networks:
  tasknet: {}